version: "3.8"

services:
  tg-bot:
    container_name: wishlist-env-tg-bot
    image: wishlist-env-tg-bot
    build:
      context: wishlist_bot
      target: development
    volumes:
      - .:/app
    ports:
      - 4000:4000
    depends_on:
      - api

  api:
    container_name: wishlist-env-api
    image: wishlist-env-api
    build:
      context: wishlist_api
      target: development
    volumes:
      - .:/app
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    container_name: wishlist-env-db
    image: postgres:15.0
    env_file:
      - .docker.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data 

volumes:
  db:
